name: Run tests

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ 'windows', 'ubuntu', 'macos' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Restore dependencies
      run: dotnet restore QRDER/QRDER.sln
      
    - name: Build
      run: dotnet build QRDER/QRDER.sln --no-restore
      
    - name: Test
      run: dotnet test QRDER/QRDER.sln --no-build --verbosity normal
